version: "3"

services:
  immudb:
    image: codenotary/immudb:1.3-bullseye-slim
    ports:
      - "3322:3322"
      - "8081:8080"
  app:
    depends_on:
      - immudb
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      DB: immudb
